package gr.dim.stas.model.appmodule;

import gr.dim.stas.model.appmodule.common.HRModule;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 02 15:26:12 CET 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HRModuleImpl extends ApplicationModuleImpl implements HRModule {
    /**
     * This is the default constructor (do not remove).
     */
    public HRModuleImpl() {
    }

    /**
     * Container's getter for DepartmentsViewLeft.
     * @return DepartmentsViewLeft
     */
    public ViewObjectImpl getDepartmentsViewLeft() {
        return (ViewObjectImpl)findViewObject("DepartmentsViewLeft");
    }

    /**
     * Container's getter for EmployeesViewLeft.
     * @return EmployeesViewLeft
     */
    public ViewObjectImpl getEmployeesViewLeft() {
        return (ViewObjectImpl)findViewObject("EmployeesViewLeft");
    }

    /**
     * Container's getter for DepartmentsViewRight.
     * @return DepartmentsViewRight
     */
    public ViewObjectImpl getDepartmentsViewRight() {
        return (ViewObjectImpl)findViewObject("DepartmentsViewRight");
    }

    /**
     * Container's getter for EmployeesViewRight.
     * @return EmployeesViewRight
     */
    public ViewObjectImpl getEmployeesViewRight() {
        return (ViewObjectImpl)findViewObject("EmployeesViewRight");
    }

    /**
     * Container's getter for EmpDeptFkLinkLeft.
     * @return EmpDeptFkLinkLeft
     */
    public ViewLinkImpl getEmpDeptFkLinkLeft() {
        return (ViewLinkImpl)findViewLink("EmpDeptFkLinkLeft");
    }

    /**
     * Container's getter for EmpDeptFkLinkRight.
     * @return EmpDeptFkLinkRight
     */
    public ViewLinkImpl getEmpDeptFkLinkRight() {
        return (ViewLinkImpl)findViewLink("EmpDeptFkLinkRight");
    }
    
    public void executeEmpsLeft(){
       
        getEmployeesViewLeft().executeQuery();
    }
    public void executeEmpsRight(){
        
        getEmployeesViewRight().executeQuery();
        
    }

}
