package gr.dim.stas.model.appmodule.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 02 15:27:18 CET 2011
// ---------------------------------------------------------------------
public interface HRModule extends ApplicationModule {


    void executeEmpsLeft();

    void executeEmpsRight();


}
