package gr.dim.stas.model.appmodule;


import gr.dim.stas.model.appmodule.common.HRModule;

import oracle.adf.model.adapter.dataformat.csv.CSVParser;

import oracle.jbo.Row;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Nov 16 18:07:11 GMT 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HRModuleImpl extends ApplicationModuleImpl implements HRModule {
    /**
     * This is the default constructor (do not remove).
     */
    public HRModuleImpl() {
    }

    /**
     * Container's getter for CountriesView1.
     * @return CountriesView1
     */
    public ViewObjectImpl getCountriesView1() {
        return (ViewObjectImpl)findViewObject("CountriesView1");
    
    }
    /**
     * Method that creates a new row from String[] of values comging from the CSVParser.
     * @param csvParser
     */
    public void createRow(String[] lineValues){
        ViewObjectImpl countriesView1 = this.getCountriesView1();
        //skip first line
            //skip firstLine as it has the headers in this case.
                Row createRow = countriesView1.createRow();
                createRow.setAttribute("CountryId", lineValues[0]);
                createRow.setAttribute("CountryName", lineValues[1]);
                createRow.setAttribute("RegionId", lineValues[2]);
                
                countriesView1.insertRow(createRow);
                countriesView1.setCurrentRow(createRow);

    }
}
