package gr.dim.stas.model.views.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Nov 03 20:37:56 CET 2011
// ---------------------------------------------------------------------
public interface EmployeesViewRow extends Row {
    void updateDepartmentId(Integer depId);
}
