package gr.dim.stas.model.appmodule.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 23 13:02:32 CET 2011
// ---------------------------------------------------------------------
public interface HRModule extends ApplicationModule {
    void createNewRowOnDepts();
}
