package gr.dim.stas.model.appmodule.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 15 21:49:30 CET 2011
// ---------------------------------------------------------------------
public interface HRModule extends ApplicationModule {
    void createInsert();
}
