package gr.dim.stas.model.appmodule;

import gr.dim.stas.model.appmodule.common.HRModule;

import oracle.jbo.Row;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 23 12:42:48 CET 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HRModuleImpl extends ApplicationModuleImpl implements HRModule {
    /**
     * This is the default constructor (do not remove).
     */
    public HRModuleImpl() {
    }
    /**
     * method that creates a new row programmatically.
     */
    public void createNewRowOnDepts(){
        ViewObjectImpl departmentsView = getDepartmentsView1();
        Row createRow = departmentsView.createRow();
        departmentsView.insertRow(createRow);
        departmentsView.setCurrentRow(createRow);
    }
    /**
     * Container's getter for DepartmentsView1.
     * @return DepartmentsView1
     */
    public ViewObjectImpl getDepartmentsView1() {
        return (ViewObjectImpl)findViewObject("DepartmentsView1");
    }
}
