package gr.dim.stas.model.appmodule;

import gr.dim.stas.model.appmodule.common.HRModule;
import gr.dim.stas.model.views.RegionsViewImpl;

import oracle.jbo.Row;
import oracle.jbo.server.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 15 21:47:42 CET 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HRModuleImpl extends ApplicationModuleImpl implements HRModule {
    /**
     * This is the default constructor (do not remove).
     */
    public HRModuleImpl() {
    }

    /**
     * Container's getter for RegionsView1.
     * @return RegionsView1
     */
    public RegionsViewImpl getRegionsView1() {
        return (RegionsViewImpl)findViewObject("RegionsView1");
    }
    
    /**
     * Method that checks if there are any fetched rows and if not, creates a new row in the Regions View Object.
     */
    public void createInsert(){
        //check there are any records in the vo
        RegionsViewImpl vo = getRegionsView1();
        
        if(vo.getFetchedRowCount()==0){
            System.out.println("creating row...");
            //proceed with the create.
            Row createRow = vo.createRow();
            vo.insertRow(createRow);
            vo.setCurrentRow(createRow);
        }
    }
}
