package gr.dim.stas.model.appmodule.client;

import gr.dim.stas.model.appmodule.common.HRModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Nov 16 18:25:31 GMT 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HRModuleClient extends ApplicationModuleImpl implements HRModule {
    /**
     * This is the default constructor (do not remove).
     */
    public HRModuleClient() {
    }

    public void createRow(String[] lineValues) {
        Object _ret = this.riInvokeExportedMethod(this,"createRow",new String [] {"[Ljava.lang.String;"},new Object[] {lineValues});
        return;
    }
}
