package gr.dim.stas.model.appmodule.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Nov 16 18:25:31 GMT 2012
// ---------------------------------------------------------------------
public interface HRModule extends ApplicationModule {
    void createRow(String[] lineValues);
}
